/*
 * Copyright (c) 2026 hesse
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef XOS_KERNEL_PERF_COUNTER_H
#define XOS_KERNEL_PERF_COUNTER_H

#ifdef PERF
#include <stdbool.h>
#include <stdint.h>

enum perf_counter_provider {
  PERF_COUNTER_PROVIDER_BLOCK = 1U << 0,
  PERF_COUNTER_PROVIDER_FAT = 1U << 1,
  PERF_COUNTER_PROVIDER_READAHEAD = 1U << 2,
  PERF_COUNTER_PROVIDER_AHCI = 1U << 3,
  PERF_COUNTER_PROVIDER_EVENT = 1U << 4,
  PERF_COUNTER_PROVIDER_SCHED = 1U << 5,
  PERF_COUNTER_PROVIDER_OVERFLOW = 1ULL << 63,
};

enum perf_counter_id {
  PERF_COUNTER_BLOCK_SUBMITTED = 1,
  PERF_COUNTER_BLOCK_COMPLETED,
  PERF_COUNTER_BLOCK_FAILED,
  PERF_COUNTER_BLOCK_REJECTED,
  PERF_COUNTER_BLOCK_READ_CMDS,
  PERF_COUNTER_BLOCK_WRITE_CMDS,
  PERF_COUNTER_BLOCK_READ_SECTORS,
  PERF_COUNTER_BLOCK_WRITE_SECTORS,
  PERF_COUNTER_BLOCK_READ_BUCKET_1,
  PERF_COUNTER_BLOCK_READ_BUCKET_2_7,
  PERF_COUNTER_BLOCK_READ_BUCKET_8,
  PERF_COUNTER_BLOCK_READ_BUCKET_9_127,
  PERF_COUNTER_BLOCK_READ_BUCKET_128,
  PERF_COUNTER_BLOCK_WRITE_BUCKET_1,
  PERF_COUNTER_BLOCK_WRITE_BUCKET_2_7,
  PERF_COUNTER_BLOCK_WRITE_BUCKET_8,
  PERF_COUNTER_BLOCK_WRITE_BUCKET_9_127,
  PERF_COUNTER_BLOCK_WRITE_BUCKET_128,
  PERF_COUNTER_FAT_CACHE_HITS = 32,
  PERF_COUNTER_FAT_CACHE_MISSES,
  PERF_COUNTER_FAT_CACHE_WAITS,
  PERF_COUNTER_FAT_CACHE_COMMANDS,
  PERF_COUNTER_FAT_CACHE_SECTORS,
  PERF_COUNTER_FAT_DEMAND_CALLS,
  PERF_COUNTER_FAT_DEMAND_STEPS,
  PERF_COUNTER_FAT_DEMAND_RESTARTS,
  PERF_COUNTER_FAT_DEMAND_BACKTRACKS,
  PERF_COUNTER_FAT_DEMAND_INVALID,
  PERF_COUNTER_FAT_DEMAND_MAPPED,
  PERF_COUNTER_FAT_RA_CALLS,
  PERF_COUNTER_FAT_RA_STEPS,
  PERF_COUNTER_FAT_RA_RESTARTS,
  PERF_COUNTER_FAT_RA_BACKTRACKS,
  PERF_COUNTER_FAT_RA_INVALID,
  PERF_COUNTER_FAT_RA_MAPPED,
  PERF_COUNTER_RA_BATCHES = 64,
  PERF_COUNTER_RA_PAGES,
  PERF_COUNTER_RA_HITS,
  PERF_COUNTER_RA_WASTE,
  PERF_COUNTER_RA_FRAGMENT_TRUNCATIONS,
  PERF_COUNTER_RA_FALLBACKS,
  PERF_COUNTER_CAPACITY,
  PERF_COUNTER_COUNT,
  PERF_COUNTER_OVERFLOW,
  PERF_COUNTER_AHCI_SYNC_SUBMITTED = 80,
  PERF_COUNTER_AHCI_ASYNC_SUBMITTED,
  PERF_COUNTER_AHCI_COMPLETED,
  PERF_COUNTER_AHCI_ERRORS,
  PERF_COUNTER_AHCI_SYNC_WAKES,
  PERF_COUNTER_AHCI_ASYNC_WAKES,
  PERF_COUNTER_AHCI_EARLY_COMPLETES,
  PERF_COUNTER_AHCI_CROSS_CPU_WAKES,
  PERF_COUNTER_AHCI_QUEUE_FULL,
  PERF_COUNTER_AHCI_INVALID_TIMING,
  PERF_COUNTER_AHCI_QUEUE_WAIT_COUNT,
  PERF_COUNTER_AHCI_QUEUE_WAIT_CYCLES,
  PERF_COUNTER_AHCI_QUEUE_WAIT_MAX,
  PERF_COUNTER_AHCI_SERVICE_COUNT,
  PERF_COUNTER_AHCI_SERVICE_CYCLES,
  PERF_COUNTER_AHCI_SERVICE_MAX,
  PERF_COUNTER_AHCI_DEPTH_CYCLES,
  PERF_COUNTER_AHCI_DEPTH,
  PERF_COUNTER_AHCI_DEPTH_MAX,
  PERF_COUNTER_AHCI_QUEUE_WAIT_HIST_BASE = 200,
  PERF_COUNTER_AHCI_SERVICE_HIST_BASE = 232,
  PERF_COUNTER_RA_DETAIL_BASE = 300,
  PERF_COUNTER_AHCI_IRQ_STAGE_BASE = 400,
};

struct perf_counter_writer {
  void *context;
  void (*add)(void *context, uint16_t id, uint64_t value);
  void (*set_available)(void *context, uint64_t providers);
};

typedef void (*perf_counter_collector_fn)(
    const struct perf_counter_writer *writer);

void perf_counter_register_collector(perf_counter_collector_fn collector);
int perf_counter_mark(uint16_t id);
void perf_counter_capture_final(void);
bool perf_counter_is_complete(void);
uint32_t perf_counter_capture(unsigned bank, uint32_t first_sequence);
const uint8_t *perf_counter_data(unsigned bank);
#endif

#endif
