/*
 * Copyright (c) 2026 hesse
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef XOS_KERNEL_PERF_PHASE_IDS_H
#define XOS_KERNEL_PERF_PHASE_IDS_H

/* Stable IDs are part of the raw trace ABI; never renumber existing entries. */
#define PERF_PHASE_BOOT_TO_KERNEL_MAIN 1
#define PERF_PHASE_EARLY_PAGING 2
#define PERF_PHASE_EARLY_GDT 3
#define PERF_PHASE_EARLY_HIGHER_HALF 4
#define PERF_PHASE_XCORE 16
#define PERF_PHASE_MEMORY 17
#define PERF_PHASE_ACPI 18
#define PERF_PHASE_IDT 19
#define PERF_PHASE_APIC_TSC 20
#define PERF_PHASE_SCHEDULER 21
#define PERF_PHASE_SMP 22
#define PERF_PHASE_VFS_CORE 32
#define PERF_PHASE_INODE 33
#define PERF_PHASE_PAGE_CACHE 34
#define PERF_PHASE_DEVTMPFS 35
#define PERF_PHASE_DRIVER 48
#define PERF_PHASE_PCI 49
#define PERF_PHASE_AHCI 50
#define PERF_PHASE_XHCI 51
#define PERF_PHASE_DRM 52
#define PERF_PHASE_BSD 64
#define PERF_PHASE_INIT_ELF 80
#define PERF_PHASE_INIT 96
#define PERF_PHASE_SERVICE_SYSLOGD 97
#define PERF_PHASE_SERVICE_EVDEV 98
#define PERF_PHASE_SERVICE_UDEVD 99
#define PERF_PHASE_SERVICE_SEATD 100
#define PERF_PHASE_SERVICE_COMPOSITOR 101
#define PERF_PHASE_SERVICE_DESKTOP 102
#define PERF_PHASE_SERVICE_SHELL 103
#define PERF_PHASE_TEST_RUNNER 112
#define PERF_PHASE_TEST_CASE 113

#endif
